### PR TITLE
Cubemaps have 2D faces

### LINKED ISSUE #226: Cubemap wants too many pixels
```rust
let pixels = [0; 256 * 256];
texture.upload_part_raw(
    GenMipmaps::Yes,
    ([0, 0], CubeFace::PositiveX),
    256,
    &pixels,
).unwrap();
```

Trying to upload an image to one of the faces on a cubemap, it fails with `NotEnoughPixels(50331648, 65536)`.
50331648 is 256 * 256 * 256 * 3, so it seems like it expects a three dimensional texture.

### PR DESCRIPTION
**Pull request by iwikal**
this fixes #226

### CODE REVIEW

File: luminance/src/texture.rs [hunk 1]
```diff
@@ -398,7 +399,7 @@ impl Dimensionable for Cubemap {
 
   fn count(size: Self::Size) -> usize {
     let size = size as usize;
-    size * size * size
```
Comment (phaazon) [inline luminance/src/texture.rs]: Ah, that seems logical. Nice catch.
